pool: 'default'

variables:
  node.version: '20.x'
  projectRoot: '.'

steps:
  - task: NodeTool@0
    displayName: 'Use Node.js $(node.version)'
    inputs:
      versionSpec: '$(node.version)'

  - script: |
      npm install
      npm install ts-config
      npm install ts-node tsconfig-paths
    workingDirectory: $(projectRoot)
    displayName: "Install dependencies"
  
  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(projectRoot)'
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      replaceExistingArchive: true
  
  - task: AzureWebApp@1
    displayName: 'Deploy Azure Web App'
    inputs:
      azureSubscription: 'script-squad-service-connection'
      appType: 'webAppLinux'
      appName: "atc-2024-scriptsquad-be-linux-web-app"
      runtimeStack: 'NODE|20.x'
      package: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      startUpCommand: 'npm start'